<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Asp.Net.Core.Learning.AspireServer\Asp.Net.Core.Learning.AspireServer.ServiceDefaults\Asp.Net.Core.Learning.AspireServer.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
